name: SecondComplex

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - run: date

  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - run: date

  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - run: date
      

  job4:
    depends: [job1, job2, job3]
    name: Fourth job
    runs-on: ubuntu-latest
    steps:
    - run: date


